eproba/apps/blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.PostList.as_view(), name="news"),
    path("<slug:slug>/", views.PostDetail.as_view(), name="post_detail"),
]

eproba/apps/worksheets/urls.py
from django.urls import path

from . import views

app_name = "worksheets"
urlpatterns = [
    path("", views.view_worksheets, name="worksheets"),
    path("s/<uuid:id>/", views.view_shared_worksheet, name="worksheet_detail"),
    path("archive/", views.archive, name="archive"),
    path("create/", views.create_worksheet, name="create_worksheet"),
    path("create-template/", views.create_template, name="create_template"),
    path("edit/<uuid:worksheet_id>/", views.edit_worksheet, name="edit_worksheet"),
    path(
        "edit-template/<uuid:worksheet_id>/", views.edit_template, name="edit_template"
    ),
    path("manage/", views.manage_worksheets, name="manage_worksheets"),
    path("print/<uuid:id>/", views.print_worksheet, name="print_worksheet"),
    path(
        "print-template/<uuid:id>/",
        views.print_worksheet_template,
        name="print_worksheet_template",
    ),
    path(
        "share/view/<uuid:id>/",
        views.view_shared_worksheet,
        name="view_shared_worksheets",
    ),
    path("tasks/check/", views.check_tasks, name="check_tasks"),
    path("templates/", views.templates, name="templates"),
    path(
        "templates/<uuid:id>/print/",
        views.print_worksheet_template,
        name="print_template",
    ),
    path("<uuid:id>/print/", views.print_worksheet, name="print_worksheet"),
    path(
        "<uuid:worksheet_id>/task/<uuid:task_id>/accept/",
        views.accept_task,
        name="accept_task",
    ),
    path(
        "<uuid:worksheet_id>/task/<uuid:task_id>/reject/",
        views.reject_task,
        name="reject_task",
    ),
    path("<uuid:worksheet_id>/tasks/sent/", views.sent_tasks, name="sent_tasks"),
    path("<uuid:worksheet_id>/task/submit/", views.submit_task, name="submit_task"),
    path(
        "<uuid:worksheet_id>/<uuid:task_id>/task/unsubmit/",
        views.unsubmit_task,
        name="unsubmit_task",
    ),
]

eproba/eproba/urls.py
from apps.blog.api.views import PostViewSet
from apps.blog.sitemaps import PostSitemap
from apps.core.api.views import ApiConfigView, ContactAPIView
from apps.core.views import FrontPageView, contactView, fcm_sw, site_management
from apps.teams.api.views import (
    DistrictViewSet,
    PatrolViewSet,
    TeamRequestViewSet,
    TeamStatisticsAPIView,
    TeamViewSet,
)
from apps.users.api.views import (
    ChangePasswordView,
    CurrentUserViewSet,
    ResendVerificationEmailView,
    UserViewSet,
    VerifyEmailView,
)
from apps.users.oauth_views import AuthorizationView as CustomAuthorizationView
from apps.users.views import (
    change_password,
    delete_account,
    edit_profile,
    finish_signup,
    google_auth_receiver,
    password_reset_complete,
    password_reset_done,
    send_verification_email,
    set_password,
    signup,
    verify_email,
    view_profile,
)
from apps.worksheets.api.views import (
    LegacyTaskViewSet,
    SubmitTask,
    TasksToBeChecked,
    TaskViewSet,
    TemplateWorksheetViewSet,
    UnsubmitTask,
    WorksheetViewSet,
)
from django.conf import settings
from django.conf.urls.static import static

# from apps.users.views.login_hub import login_from_hub, login_hub
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetConfirmView,
    PasswordResetView,
)
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from oauth2_provider.urls import app_name as oauth2_app_name
from oauth2_provider.urls import base_urlpatterns as oauth2_base_urlpatterns
from oauth2_provider.urls import oidc_urlpatterns
from rest_framework import routers

from .sitemaps import Sitemap
from .utils import (
    LegacyApiConfigView,
)

handler404 = "apps.core.views.handler404"
handler500 = "apps.core.views.handler500"

# Routers provide a way of automatically determining the URL conf.
api = routers.DefaultRouter()
api.register(r"fcm/devices", FCMDeviceAuthorizedViewSet, "fcm_devices")
api.register(r"worksheets", WorksheetViewSet, "api-worksheets")
api.register(r"templates", TemplateWorksheetViewSet, "api-templates")
api.register(r"users", UserViewSet, "api-users")
api.register(r"districts", DistrictViewSet, "api-districts")
api.register(r"teams", TeamViewSet, "api-teams")
api.register(r"patrols", PatrolViewSet, "api-patrols")
api.register(r"team-requests", TeamRequestViewSet, basename="team-requests")
api.register("news", PostViewSet, basename="news")

sitemaps = {
    "posts": PostSitemap,
    "static": Sitemap,
}
admin.site.site_title = "EPRÓBA"
admin.site.site_header = "Panel administratora" + " - DEV" if settings.DEV else ""
urlpatterns = [
    path("", FrontPageView.as_view(), name="frontpage"),
    path("firebase-messaging-sw.js", fcm_sw, name="fcm_sw"),
    path(
        "about/", TemplateView.as_view(template_name="sites/about.html"), name="about"
    ),
    path(
        "gdpr/",
        TemplateView.as_view(template_name="sites/gdpr.html"),
        name="gdpr",
    ),
    path(
        "privacy-policy/",
        TemplateView.as_view(template_name="sites/privacy_policy.html"),
        name="privacy-policy",
    ),
    path(
        "terms-of-service/",
        TemplateView.as_view(template_name="sites/terms_of_service.html"),
        name="terms",
    ),
    path(
        "terms/gdpr/",
        TemplateView.as_view(template_name="sites/gdpr.html"),
        name="gdpr",
    ),
    path(
        "terms/privacy-policy/",
        TemplateView.as_view(template_name="sites/privacy_policy.html"),
        name="privacy-policy",
    ),
    path(
        "terms/terms-of-service/",
        TemplateView.as_view(template_name="sites/terms_of_service.html"),
        name="terms",
    ),
    path("admin/", admin.site.urls, name="admin"),
    path("api/", include(api.urls)),
    path("api/api-config/", LegacyApiConfigView.as_view()),
    path("api/config/", ApiConfigView.as_view()),
    path(
        "api/user/",
        CurrentUserViewSet.as_view(
            {"get": "retrieve", "patch": "partial_update", "delete": "destroy"}
        ),
    ),
    path("api/user/password/", ChangePasswordView.as_view(), name="change_password"),
    path("api/user/verify-email/", VerifyEmailView.as_view(), name="api_verify_email"),
    path(
        "api/user/verify-email/resend/",
        ResendVerificationEmailView.as_view(),
        name="api_resend_verification_email",
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/task/<uuid:id>/",  # Outdated URL
        LegacyTaskViewSet.as_view({"get": "retrieve", "patch": "partial_update"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/",
        TaskViewSet.as_view({"get": "retrieve", "patch": "partial_update"}),
    ),
    path("api/worksheets/tasks/tbc/", TasksToBeChecked.as_view()),
    path(
        "api/worksheets/<uuid:worksheet_id>/task/<uuid:id>/submit",
        SubmitTask.as_view(),  # Legacy separate view
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/task/<uuid:id>/unsubmit",  # Outdated URL
        UnsubmitTask.as_view(),  # Legacy separate view
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/submit/",
        TaskViewSet.as_view({"post": "submit"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/unsubmit/",
        TaskViewSet.as_view({"post": "unsubmit"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/accept/",
        TaskViewSet.as_view({"post": "accept"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/reject/",
        TaskViewSet.as_view({"post": "reject"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/clear-status/",
        TaskViewSet.as_view({"post": "clear_status"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/approvers/",
        TaskViewSet.as_view({"get": "get_approvers"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/note/",
        TaskViewSet.as_view(
            {"post": "manage_note", "put": "manage_note", "delete": "manage_note"}
        ),
    ),
    path("api/contact/", ContactAPIView.as_view(), name="contact"),
    path(
        "api/team-statistics/",
        TeamStatisticsAPIView.as_view(),
        name="team_statistics_api",
    ),
    path("contact/", contactView, name="contact"),
    path("worksheets/", include("apps.worksheets.urls")),
    path(
        "api/login/",
        LoginView.as_view(
            template_name="users/login.html", redirect_authenticated_user=True
        ),
        name="login",
    ),
    path("api/logout/", LogoutView.as_view(), name="logout"),
    # path("lh/", login_hub),
    # path("_login/<uuid:user_id>/", login_from_hub),
    path("news/", include("apps.blog.urls")),
    path(
        "api/password-reset/",
        PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "api/password-reset-complete/",
        password_reset_complete,
        name="password_reset_complete",
    ),
    path(
        "api/password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path("api/password-reset-done/", password_reset_done, name="password_reset_done"),
    path("profile/edit/", edit_profile, name="edit_profile"),
    path("profile/change-password/", change_password, name="change_password"),
    path("profile/set-password/", set_password, name="set_password"),
    path("profile/view/", view_profile, name="view_profile", kwargs={"user_id": None}),
    path("profile/view/<uuid:user_id>/", view_profile, name="view_profile"),
    path("profile/delete/", delete_account, name="delete_account"),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("api/signup/", signup, name="signup"),
    path("api/signup/finalize/", finish_signup, name="finish_signup"),
    path("team/", include("apps.teams.urls")),
    path(
        "oauth2/authorize/", CustomAuthorizationView.as_view(), name="oauth2_authorize"
    ),
    path(
        "oauth2/",
        include(
            (oauth2_base_urlpatterns + oidc_urlpatterns, oauth2_app_name),
            namespace="oauth2_provider",
        ),
    ),
    path("site-management/", site_management, name="site_management"),
    path(
        "app-ads.txt",
        RedirectView.as_view(url=staticfiles_storage.url("app-ads.txt")),
    ),
    path(
        "ads.txt",
        RedirectView.as_view(url=staticfiles_storage.url("ads.txt")),
    ),
    path(
        "api/google-auth-receiver/",
        google_auth_receiver,
        name="google_auth_receiver",
    ),
    path(
        "send-verification-email/",
        send_verification_email,
        name="send_verification_email",
    ),
    path(
        "verify-email/<uuid:user_id>/<uuid:token>/", verify_email, name="verify_email"
    ),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("tinymce/", include("tinymce.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eproba/apps/core/models.py
# Create your models here.

eproba/apps/core/forms.py
from django import forms
from django.forms import EmailInput, Textarea, TextInput


class ContactForm(forms.Form):
    from_email = forms.EmailField(
        widget=EmailInput(),
        required=True,
        label="Twój email",
    )
    subject = forms.CharField(
        widget=TextInput(),
        required=True,
        label="Temat",
    )
    message = forms.CharField(
        widget=Textarea({"rows": 5}),
        required=True,
        label="Wiadomość",
    )

eproba/apps/core/api/views.py
from constance import config
from django.conf import settings
from django.core.mail import EmailMessage
from rest_framework import permissions, status
from rest_framework.exceptions import APIException
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response
from rest_framework.views import APIView

from eproba import __version__ as eproba_version  # noqa: F401

from .serializers import ContactSerializer


class ContactAPIView(GenericAPIView):
    serializer_class = ContactSerializer

    def post(self, request):
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            subject = serializer.validated_data["subject"]
            from_email = serializer.validated_data["from_email"]
            message = serializer.validated_data["message"]
            type_ = serializer.validated_data.get("type", "general")

            if type_ == "bug":
                subject = "[Zgłoszenie błędu] " + subject

            try:
                email = EmailMessage(
                    subject=subject,
                    body=message,
                    from_email=None,
                    to=["eproba@zhr.pl"],
                    headers={"Reply-To": from_email},
                )
                email.send()
                return Response(
                    {"message": "Wiadomość została wysłana."}, status=status.HTTP_200_OK
                )
            except Exception as e:
                raise APIException(str(e), code=status.HTTP_500_INTERNAL_SERVER_ERROR)

        raise APIException(detail=serializer.errors, code=status.HTTP_400_BAD_REQUEST)


class ApiConfigView(APIView):
    permission_classes = (permissions.AllowAny,)

    def get(self, request):
        return Response(
            {
                "maintenance": config.MAINTENANCE_MODE,
                "server_version": eproba_version,
                "api_version": settings.API_VERSION,
            }
        )

eproba/apps/core/views.py
from apps.blog.models import Post
from constance import config
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import BadHeaderError, EmailMessage
from django.http import HttpResponse
from django.shortcuts import redirect, render, reverse
from django.views import generic

from .forms import ContactForm


def handler404(request, exception):
    return render(request, "errors/404.html", status=404)


def handler500(request):
    return render(request, "errors/500.html", status=500)


class FrontPageView(generic.ListView):
    template_name = "core/frontpage.html"

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Post.objects.filter(status=1, minimum_function=0).order_by(
                "-created_on"
            )

        return Post.objects.filter(
            status=1, minimum_function__lte=self.request.user.function
        ).order_by("-created_on")


def contactView(request):
    if request.method == "GET":
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data["subject"]
            from_email = form.cleaned_data["from_email"]
            message = form.cleaned_data["message"]
            try:
                email = EmailMessage(
                    subject=subject,
                    body=message,
                    from_email=None,  # Use the default email from settings
                    to=["eproba@zhr.pl"],
                    headers={"Reply-To": from_email},  # Set Reply-To header
                )
                email.send()
            except BadHeaderError:
                return HttpResponse("Invalid header found.")
            messages.info(request, "Wiadomość została wysłana.")
            return redirect(reverse("frontpage"))
    return render(request, "sites/contact/email.html", {"form": form})


def fcm_sw(request):
    return render(
        request, "firebase-messaging-sw.js", content_type="application/javascript"
    )


@login_required
def site_management(request):
    if not request.user.is_superuser:
        return redirect(reverse("frontpage"))
    if request.method == "POST":
        config.ADS_WEB = bool(request.POST.get("ads_web", False))
        config.ADS_MOBILE = bool(request.POST.get("ads_mobile", False))
        config.WEB_MAINTENANCE_MODE = bool(request.POST.get("maintenance_web", False))
        config.API_MAINTENANCE_MODE = bool(request.POST.get("maintenance_api", False))
        config.MINIMUM_APP_VERSION = request.POST.get("min_app_version", "0")
        config.REQUIRE_EMAIL_VERIFICATION = bool(
            request.POST.get("require_email_verification", False)
        )
        return redirect(reverse("site_management"))
    return render(request, "sites/site_management.html")

eproba/apps/core/templates/core/base.html
<!DOCTYPE html>
<html lang="pl">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta name="google-site-verification" content="Oa-8rANmBab3FrKyY44hIe4K1937-KdaX9UEZLJs9bg"/>
    <title>{% if dev_mode %}DEV - {% endif %}{% block title %}Epróba{% endblock %}</title>
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css"
    >
    <link rel="preload" href="{% static 'css/bulma-tooltip.min.css' %}" as="style"
          onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link rel="stylesheet" href="{% static 'css/bulma-tooltip.min.css' %}">
    </noscript>
    <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet" type="text/css">
    <script async src="https://kit.fontawesome.com/a00f1140b1.js" crossorigin="anonymous"></script>
    <script defer src="https://cdn.rawgit.com/davidshimjs/qrcodejs/gh-pages/qrcode.min.js"></script>
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/UAParser.js/1.0.32/ua-parser.min.js"
            integrity="sha512-QyFNWdGOdhSDvdDfS8tzVVg+UgnwLYmPybDSityYxHUg7mTVrw5dWRYdiUHNUOWVtLkJqTB8/LhrUCRPfkrEFg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/core/navbar.js' %}"></script>
    <script src="https://accounts.google.com/gsi/client" async></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'images/icons/favicon.svg' %}" type="image/svg+xml">
    <meta name="title" content="Epróba">
    <meta name="description"
          content="Epróba – kompleksowy system zarządzania próbami na stopnie w drużynie harcerskiej. Umożliwia tworzenie, edytowanie i zatwierdzanie prób, śledzenie postępów harcerzy oraz wygodne zarządzanie stopniami. Dzięki dostępności online i w aplikacji mobilnej, harcerze zawsze mają swoje próby pod ręką, a kadra może na bieżąco monitorować ich postępy. System eliminuje problem zgubionych kart prób i usprawnia pracę w drużynie. Zarejestruj swoją drużynę już dziś!">
    <meta name="keywords"
          content="harcerstwo, próby na stopnie, epróba, stopnie harcerskie, zarządzanie próbami, ZHR, system harcerski, aplikacja harcerska, drużyna harcerska, postępy harcerzy, szablony prób, harcerze, harcerska aplikacja, grywalizacja harcerska, harcerskie rankingi, e-proba, harcerskie stopnie, epróba ZHR, cyfrowe próby harcerskie, organizacja w drużynie, scouting, scouting app">
    <meta name="robots" content="index, follow">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="language" content="English">
    <meta name="author" content="Antoni Czaplicki">


    <meta property="og:title" content="Epróba">
    <meta property="og:description"
          content="Zarządzanie próbami na stopnie w harcerstwie jeszcze nigdy nie było tak proste! Twórz, edytuj i śledź postępy w jednym miejscu. Przekonaj się sam!">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://eproba.zhr.pl/">
    <meta property="og:image" content="https://eproba.zhr.pl/api/static/images/logo-background-200x200.png">
    <meta property="og:locale" content="pl_PL">

    <!-- Google Tag Manager -->
    {% if not request.GET.embed %}
        <script>(function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-NN3D54WV');</script>
    {% endif %}
    <!-- End Google Tag Manager -->

    {% block extrahead %}
    {% endblock %}
    <script>
        const csrfToken = "{{ csrf_token }}";
    </script>
    {% if request.user.is_authenticated and not request.GET.embed %}
        <script async type="module" src="{% static 'js/core/firebase.js' %}"></script>
    {% endif %}
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NN3D54WV"
            height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
{% if dev_mode %}
    <div style="
        position: fixed;
        top: 32px;
        right: 0;
        background: red;
        color: white;
        padding: 4px 50px;
        font-weight: bold;
        font-size: 16px;
        transform: rotate(45deg) translate(43px, -10px);
        transform-origin: top right;
        z-index: 9999;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.3);
    ">
        DEV
    </div>
{% endif %}
{% if not request.user.is_authenticated and google_auth_enabled and not request.GET.embed %}
    <div id="g_id_onload"
         data-client_id="897419344971-f2uj5udmpk698ur529di5ens7ufogclg.apps.googleusercontent.com"
         data-context="use"
         data-ux_mode="redirect"
         data-login_uri="{% if request.is_secure %}https://{{ request.get_host }}{% endif %}{% url 'google_auth_receiver' %}"
         data-state="{{ request.get_full_path }}"
         data-itp_support="true">
    </div>
{% endif %}
<div {% if not request.GET.embed %} class="container" id="container" {% endif %}
                                    style="display: flex; flex-direction: column;">
    {% if not request.GET.embed and not request.path|slice:5 == '/api/' %}
        {% include "core/navbar.html" %}
    {% endif %}
    <br>
    {% block subnavbarcontent %}
    {% endblock %}
    <div {% if not request.GET.embed %} class="container px-3" {% else %} class="px-4" {% endif %}
                                        style="position: relative; {% if not request.GET.embed and not request.path|slice:5 == '/api/' %} margin-bottom: 10vh {% endif %};display: flex; flex-direction: column;width: 100%;">
        {% block content %}
        {% endblock %}
    </div>
</div>
<div id="notifications" style="z-index: 50; position: fixed; bottom: 10px; right: 10px"></div>
{% if not request.GET.embed %}
    {% block footer %}
        <div class="footer" style="background-color:transparent; padding: 1rem 5rem 1rem">
            <div style="border-top: 1px solid #a1a1a180; padding-bottom: 0.5rem"></div>
            <p class="has-text-centered">
                <strong>Epróba</strong> by <a href="https://github.com/Antoni-Czaplicki">Antoni Czaplicki</a>. Source
                code
                is available on <a href="https://github.com/eproba">Github</a>.
            </p>
        </div>
    {% endblock %}
{% endif %}
</body>
</html>

eproba/apps/core/templates/core/frontpage.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="box">
        <p>Witaj na stronie Epróba, aby zobaczyć swoje próby wejdź w zakadkę <a
                href="{% url 'worksheets:worksheets' %}">"Twoje
            próby"</a>.</p>
        <p>Jeśli jeszcze nie wiesz jak rozpocząć swoją przygodę z Epróbą to zapraszamy cię do skorzystania z
            przygotowanych przez naszych ekspertów <a href="/news/tutorial">samouczków</a> które pomogą ci założyć swoje
            nowe konto, utworzyć pierwszą próbę i wiele więcej.</p>
    </div>
    <div class="block">
        <h1 class="title has-text-weight-bold">Aktualności</h1>
        <div class="container" id="blog">
            <div class="row">
                <div>
                    {% for post in post_list %}
                        <div class="block card" onclick="location.href='{% url 'blog:post_detail' post.slug %}'"
                             style="cursor: pointer;">
                            <div class="card-content">
                                <div class="media">
                                    <div class="media-content">
                                        <p class="title is-4">{{ post.title }}</p>
                                        <p class="subtitle is-6">{{ post.created_on }}</p>
                                    </div>
                                </div>

                                <div class="content">{{ post.content | safe }}</div>
                            </div>
                        </div>
                    {% endfor %}
                    {% if not post_list %}
                        <div class="block">
                            <p>Brak aktualności</p>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}