eproba/apps/worksheets/urls.py
from django.urls import path

from . import views

app_name = "worksheets"
urlpatterns = [
    path("", views.view_worksheets, name="worksheets"),
    path("s/<uuid:id>/", views.view_shared_worksheet, name="worksheet_detail"),
    path("archive/", views.archive, name="archive"),
    path("create/", views.create_worksheet, name="create_worksheet"),
    path("create-template/", views.create_template, name="create_template"),
    path("edit/<uuid:worksheet_id>/", views.edit_worksheet, name="edit_worksheet"),
    path(
        "edit-template/<uuid:worksheet_id>/", views.edit_template, name="edit_template"
    ),
    path("manage/", views.manage_worksheets, name="manage_worksheets"),
    path("print/<uuid:id>/", views.print_worksheet, name="print_worksheet"),
    path(
        "print-template/<uuid:id>/",
        views.print_worksheet_template,
        name="print_worksheet_template",
    ),
    path(
        "share/view/<uuid:id>/",
        views.view_shared_worksheet,
        name="view_shared_worksheets",
    ),
    path("tasks/check/", views.check_tasks, name="check_tasks"),
    path("templates/", views.templates, name="templates"),
    path(
        "templates/<uuid:id>/print/",
        views.print_worksheet_template,
        name="print_template",
    ),
    path("<uuid:id>/print/", views.print_worksheet, name="print_worksheet"),
    path(
        "<uuid:worksheet_id>/task/<uuid:task_id>/accept/",
        views.accept_task,
        name="accept_task",
    ),
    path(
        "<uuid:worksheet_id>/task/<uuid:task_id>/reject/",
        views.reject_task,
        name="reject_task",
    ),
    path("<uuid:worksheet_id>/tasks/sent/", views.sent_tasks, name="sent_tasks"),
    path("<uuid:worksheet_id>/task/submit/", views.submit_task, name="submit_task"),
    path(
        "<uuid:worksheet_id>/<uuid:task_id>/task/unsubmit/",
        views.unsubmit_task,
        name="unsubmit_task",
    ),
]

eproba/eproba/urls.py
from apps.blog.api.views import PostViewSet
from apps.blog.sitemaps import PostSitemap
from apps.core.api.views import ApiConfigView, ContactAPIView
from apps.core.views import FrontPageView, contactView, fcm_sw, site_management
from apps.teams.api.views import (
    DistrictViewSet,
    PatrolViewSet,
    TeamRequestViewSet,
    TeamStatisticsAPIView,
    TeamViewSet,
)
from apps.users.api.views import (
    ChangePasswordView,
    CurrentUserViewSet,
    ResendVerificationEmailView,
    UserViewSet,
    VerifyEmailView,
)
from apps.users.oauth_views import AuthorizationView as CustomAuthorizationView
from apps.users.views import (
    change_password,
    delete_account,
    edit_profile,
    finish_signup,
    google_auth_receiver,
    password_reset_complete,
    password_reset_done,
    send_verification_email,
    set_password,
    signup,
    verify_email,
    view_profile,
)
from apps.worksheets.api.views import (
    LegacyTaskViewSet,
    SubmitTask,
    TasksToBeChecked,
    TaskViewSet,
    TemplateWorksheetViewSet,
    UnsubmitTask,
    WorksheetViewSet,
)
from django.conf import settings
from django.conf.urls.static import static

# from apps.users.views.login_hub import login_from_hub, login_hub
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetConfirmView,
    PasswordResetView,
)
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from oauth2_provider.urls import app_name as oauth2_app_name
from oauth2_provider.urls import base_urlpatterns as oauth2_base_urlpatterns
from oauth2_provider.urls import oidc_urlpatterns
from rest_framework import routers

from .sitemaps import Sitemap
from .utils import (
    LegacyApiConfigView,
)

handler404 = "apps.core.views.handler404"
handler500 = "apps.core.views.handler500"

# Routers provide a way of automatically determining the URL conf.
api = routers.DefaultRouter()
api.register(r"fcm/devices", FCMDeviceAuthorizedViewSet, "fcm_devices")
api.register(r"worksheets", WorksheetViewSet, "api-worksheets")
api.register(r"templates", TemplateWorksheetViewSet, "api-templates")
api.register(r"users", UserViewSet, "api-users")
api.register(r"districts", DistrictViewSet, "api-districts")
api.register(r"teams", TeamViewSet, "api-teams")
api.register(r"patrols", PatrolViewSet, "api-patrols")
api.register(r"team-requests", TeamRequestViewSet, basename="team-requests")
api.register("news", PostViewSet, basename="news")

sitemaps = {
    "posts": PostSitemap,
    "static": Sitemap,
}
admin.site.site_title = "EPRÓBA"
admin.site.site_header = "Panel administratora" + " - DEV" if settings.DEV else ""
urlpatterns = [
    path("", FrontPageView.as_view(), name="frontpage"),
    path("firebase-messaging-sw.js", fcm_sw, name="fcm_sw"),
    path(
        "about/", TemplateView.as_view(template_name="sites/about.html"), name="about"
    ),
    path(
        "gdpr/",
        TemplateView.as_view(template_name="sites/gdpr.html"),
        name="gdpr",
    ),
    path(
        "privacy-policy/",
        TemplateView.as_view(template_name="sites/privacy_policy.html"),
        name="privacy-policy",
    ),
    path(
        "terms-of-service/",
        TemplateView.as_view(template_name="sites/terms_of_service.html"),
        name="terms",
    ),
    path(
        "terms/gdpr/",
        TemplateView.as_view(template_name="sites/gdpr.html"),
        name="gdpr",
    ),
    path(
        "terms/privacy-policy/",
        TemplateView.as_view(template_name="sites/privacy_policy.html"),
        name="privacy-policy",
    ),
    path(
        "terms/terms-of-service/",
        TemplateView.as_view(template_name="sites/terms_of_service.html"),
        name="terms",
    ),
    path("admin/", admin.site.urls, name="admin"),
    path("api/", include(api.urls)),
    path("api/api-config/", LegacyApiConfigView.as_view()),
    path("api/config/", ApiConfigView.as_view()),
    path(
        "api/user/",
        CurrentUserViewSet.as_view(
            {"get": "retrieve", "patch": "partial_update", "delete": "destroy"}
        ),
    ),
    path("api/user/password/", ChangePasswordView.as_view(), name="change_password"),
    path("api/user/verify-email/", VerifyEmailView.as_view(), name="api_verify_email"),
    path(
        "api/user/verify-email/resend/",
        ResendVerificationEmailView.as_view(),
        name="api_resend_verification_email",
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/task/<uuid:id>/",  # Outdated URL
        LegacyTaskViewSet.as_view({"get": "retrieve", "patch": "partial_update"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/",
        TaskViewSet.as_view({"get": "retrieve", "patch": "partial_update"}),
    ),
    path("api/worksheets/tasks/tbc/", TasksToBeChecked.as_view()),
    path(
        "api/worksheets/<uuid:worksheet_id>/task/<uuid:id>/submit",
        SubmitTask.as_view(),  # Legacy separate view
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/task/<uuid:id>/unsubmit",  # Outdated URL
        UnsubmitTask.as_view(),  # Legacy separate view
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/submit/",
        TaskViewSet.as_view({"post": "submit"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/unsubmit/",
        TaskViewSet.as_view({"post": "unsubmit"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/accept/",
        TaskViewSet.as_view({"post": "accept"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/reject/",
        TaskViewSet.as_view({"post": "reject"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/clear-status/",
        TaskViewSet.as_view({"post": "clear_status"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/approvers/",
        TaskViewSet.as_view({"get": "get_approvers"}),
    ),
    path(
        "api/worksheets/<uuid:worksheet_id>/tasks/<uuid:id>/note/",
        TaskViewSet.as_view(
            {"post": "manage_note", "put": "manage_note", "delete": "manage_note"}
        ),
    ),
    path("api/contact/", ContactAPIView.as_view(), name="contact"),
    path(
        "api/team-statistics/",
        TeamStatisticsAPIView.as_view(),
        name="team_statistics_api",
    ),
    path("contact/", contactView, name="contact"),
    path("worksheets/", include("apps.worksheets.urls")),
    path(
        "api/login/",
        LoginView.as_view(
            template_name="users/login.html", redirect_authenticated_user=True
        ),
        name="login",
    ),
    path("api/logout/", LogoutView.as_view(), name="logout"),
    # path("lh/", login_hub),
    # path("_login/<uuid:user_id>/", login_from_hub),
    path("news/", include("apps.blog.urls")),
    path(
        "api/password-reset/",
        PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "api/password-reset-complete/",
        password_reset_complete,
        name="password_reset_complete",
    ),
    path(
        "api/password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path("api/password-reset-done/", password_reset_done, name="password_reset_done"),
    path("profile/edit/", edit_profile, name="edit_profile"),
    path("profile/change-password/", change_password, name="change_password"),
    path("profile/set-password/", set_password, name="set_password"),
    path("profile/view/", view_profile, name="view_profile", kwargs={"user_id": None}),
    path("profile/view/<uuid:user_id>/", view_profile, name="view_profile"),
    path("profile/delete/", delete_account, name="delete_account"),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("api/signup/", signup, name="signup"),
    path("api/signup/finalize/", finish_signup, name="finish_signup"),
    path("team/", include("apps.teams.urls")),
    path(
        "oauth2/authorize/", CustomAuthorizationView.as_view(), name="oauth2_authorize"
    ),
    path(
        "oauth2/",
        include(
            (oauth2_base_urlpatterns + oidc_urlpatterns, oauth2_app_name),
            namespace="oauth2_provider",
        ),
    ),
    path("site-management/", site_management, name="site_management"),
    path(
        "app-ads.txt",
        RedirectView.as_view(url=staticfiles_storage.url("app-ads.txt")),
    ),
    path(
        "ads.txt",
        RedirectView.as_view(url=staticfiles_storage.url("ads.txt")),
    ),
    path(
        "api/google-auth-receiver/",
        google_auth_receiver,
        name="google_auth_receiver",
    ),
    path(
        "send-verification-email/",
        send_verification_email,
        name="send_verification_email",
    ),
    path(
        "verify-email/<uuid:user_id>/<uuid:token>/", verify_email, name="verify_email"
    ),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("tinymce/", include("tinymce.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eproba/apps/worksheets/views/archive.py
from apps.teams.models import Patrol
from apps.users.utils import min_function, patrol_required
from apps.worksheets.models import Worksheet
from apps.worksheets.utils import prepare_worksheet
from django.shortcuts import render


@patrol_required
@min_function(2)
def archive(request):
    user = request.user
    worksheets = []
    if request.user.function == 2:
        worksheets.extend(
            prepare_worksheet(worksheet)
            for worksheet in Worksheet.objects.filter(
                user__patrol__team__id=user.patrol.team.id,
                user__function__lt=user.function,
                is_archived=True,
                deleted=False,
            ).exclude(user=user)
        )

    elif request.user.function in [3, 4]:
        worksheets.extend(
            prepare_worksheet(worksheet)
            for worksheet in Worksheet.objects.filter(
                user__patrol__team__id=user.patrol.team.id,
                is_archived=True,
                deleted=False,
            )
        )

    elif request.user.function >= 5:
        worksheets.extend(
            prepare_worksheet(worksheet)
            for worksheet in Worksheet.objects.filter(
                user__patrol__team__id=user.patrol.team.id,
                is_archived=True,
                deleted=False,
            )
        )

    worksheets.extend(
        prepare_worksheet(worksheet)
        for worksheet in Worksheet.objects.filter(
            supervisor__id=user.id, is_archived=True, deleted=False
        )
    )

    patrols = Patrol.objects.filter(team__id=user.patrol.team.id).order_by("name")
    return render(
        request,
        "worksheets/archive.html",
        {"user": user, "worksheets_list": worksheets, "patrols": patrols},
    )

eproba/apps/worksheets/views/create_template.py
from apps.users.utils import min_function, patrol_required
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms import formset_factory
from django.shortcuts import redirect, render
from django.urls import reverse

from ..forms import (
    ExtendedTemplateWorksheetCreateForm,
    TemplateTaskForm,
    TemplateWorksheetCreateForm,
)
from ..models import TemplateTask


@login_required
@patrol_required
@min_function(2)
def create_template(request):
    task_form_set = formset_factory(TemplateTaskForm, extra=3)
    if request.method == "POST":
        if request.user.is_staff and request.user.has_perm(
            "worksheets.add_templateworksheet"
        ):
            worksheet_template = ExtendedTemplateWorksheetCreateForm(request.POST)
        else:
            worksheet_template = TemplateWorksheetCreateForm(request.POST)
        tasks = task_form_set(request.POST)
        if worksheet_template.is_valid():
            worksheet_template_obj = worksheet_template.save(commit=False)
            if (
                worksheet_template.cleaned_data.get("for_organization")
                and request.user.is_staff
                and request.user.has_perm("worksheets.add_templateworksheet")
            ):
                worksheet_template_obj.team = None
                worksheet_template_obj.organization = (
                    request.user.patrol.team.organization
                )
            else:
                worksheet_template_obj.team = request.user.patrol.team
                worksheet_template_obj.organization = None
            worksheet_template_obj.save()
            if tasks.is_valid():
                tasks_data = tasks.cleaned_data
                for task in tasks_data:
                    if "task" in task:
                        TemplateTask.objects.create(
                            template=worksheet_template_obj,
                            task=task["task"],
                            description=task["description"],
                            template_notes=task["template_notes"],
                        )
            messages.success(request, "Szablon został utworzony")
            if request.GET.get("next", False):
                return redirect(request.GET.get("next"))
            return redirect(reverse("worksheets:templates"))

    else:
        if request.user.is_staff and request.user.has_perm(
            "worksheets.add_templateworksheet"
        ):
            worksheet_template = ExtendedTemplateWorksheetCreateForm()
        else:
            worksheet_template = TemplateWorksheetCreateForm()
        tasks = task_form_set()

    return render(
        request,
        "worksheets/create_template.html",
        {"worksheet": worksheet_template, "tasks": tasks},
    )

eproba/apps/worksheets/views/templates.py
from apps.users.utils import min_function, patrol_required
from django.db.models import Q
from django.shortcuts import render

from ..models import TemplateWorksheet


@patrol_required
@min_function(2)
def templates(request):
    worksheet_templates = []
    if request.user.is_authenticated:
        worksheet_templates = TemplateWorksheet.objects.filter(
            Q(team=request.user.patrol.team)
            | Q(team=None, organization=request.user.patrol.team.organization)
        )

    return render(
        request,
        "worksheets/templates.html",
        {"user": request.user, "worksheet_templates": worksheet_templates},
    )

eproba/apps/worksheets/templates/worksheets/check_tasks.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Prośby o zatwierdzenie{% endblock %}
{%  block extrahead %}
    <script defer src="{% static 'js/core/helpers.js' %}"></script>
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    {% if request.user.is_authenticated %}
        {% if worksheets_list %}
            {% for worksheet in worksheets_list %}
                {% if worksheet.task_list %}
                    <div class="box">
                        <h1 class="title has-text-weight-medium">{{ worksheet }}</h1>
                        {% if worksheet.supervisor %}
                            <h2 class="subtitle">Opiekun próby: <a href="{% url 'view_profile' user_id=worksheet.supervisor.user.id %}">{{ worksheet.supervisor.user.full_name_nickname }}</a></h2>
                        {% endif %}
                        <table class="table">
                            <thead>
                            <tr>
                                <th class="is-narrow">Lp.</th>
                                <th>Zadanie</th>
                                <th>Data wysłania</th>
                                <th>Akcja</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for task in worksheet.task_list %}
                                <tr>
                                    <th>{{ forloop.counter }}</th>
                                    <td>{{ task.task }}</td>
                                    <td>{{ task.approval_date }}</td>
                                    <td><span class="has-tooltip-arrow has-tooltip-left has-tooltip-success "
                                              data-tooltip="Zaakceptuj prośbę"><a
                                            onclick="confirm_popup('{% url 'worksheets:accept_task' worksheet.id task.id %}', 'Czy na pewno chcesz zaliczyć zadanie?')"><i
                                            class="far fa-check-circle" style="color:green;"></i></a></span> <span
                                            class="has-tooltip-arrow has-tooltip-left has-tooltip-danger"
                                            data-tooltip="Odrzuć prośbę"><a
                                            onclick="confirm_popup('{% url 'worksheets:reject_task' worksheet.id task.id %}', 'Czy na pewno chcesz odrzucić zadanie?')"><i
                                            class="far fa-times-circle" style="color:red;"></i></a></span></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <div class="box">
                        Nie masz żadnych prób do sprawdzenia.
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <div class="box">
                Nie masz żadnych prób do sprawdzenia.
            </div>
        {% endif %}
    {% else %}
        <div class="box">
            Aby wyświetlić swoje próby musisz się najpierw zalogować.
        </div>
    {% endif %}
{% endblock %}

eproba/apps/worksheets/templates/worksheets/request_task_check.html
{% extends 'core/base.html' %}
{% block title %}Wyślij prośbę o zatwierdzenie{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="box">
        <h1 class="title has-text-weight-medium">Poproś o zatwierdzenie zadania</h1>
        <h1 class="subtitle">{{ worksheet }}</h1>
        <form action="{% url 'worksheets:submit_task' worksheet.id %}" method="post" id="form">
            {% csrf_token %}
            {% for form in forms %}
                {{ form|crispy }}
            {% endfor %}
            <div class="field">
                <div class="control">
                    <button class="button is-primary" type="submit">Prześlij</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

eproba/apps/worksheets/templates/worksheets/sent_tasks.html
{% extends 'core/base.html' %}
{% block title %}Wysłane prośby o zatwierdzenie{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    {% if tasks_list %}
        <div class="box">
            <h1 class="title has-text-weight-medium">{{ worksheet }}</h1>
            <h2 class="subtitle">Wysłane prośby o zatwierdzenie</h2>
            <table class="table">
                <thead>
                <tr>
                    <th>Lp.</th>
                    <th>Zadanie</th>
                    <th>Zatwierdzający</th>
                    <th>Data wysłania</th>
                    <th>Akcja</th>
                </tr>
                </thead>
                <tbody>
                {% for task in tasks_list %}
                    <tr>
                        <th>{{ forloop.counter }}</th>
                        <td>{{ task.task }}</td>
                        <td>{{ task.approver }}</td>
                        <td>{{ task.approval_date }}</td>
                        <td><span class="has-tooltip-arrow has-tooltip-left has-tooltip-danger"
                                  data-tooltip="Anuluj prośbę"><a
                                onclick="confirm_unsubmit_task('{% url 'worksheets:unsubmit_task' worksheet.id task.id %}')"><i
                                class="far fa-times-circle" style="color:red;"></i></a></span></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="box">
            <div class="content">
                <h1 class="title">{{ worksheet }}</h1>
                <h2 class="subtitle">Wysłane prośby o zatwierdzenie</h2>
                <p>Nie masz wysłanych żadnych próśb o zatwierdzenie dla tej próby.</p>
                <a href="{% url 'worksheets:worksheets' %}">
                    <button class="button is-primary is-soft">
						<span class="icon">
							<i class="fas fa-clipboard-list"></i>
						</span>
                        <span>Wróć do swoich prób</span>
                    </button>
                </a>
            </div>
        </div>
    {% endif %}
    <script>
        function confirm_unsubmit_task(url) {
            var txt;
            if (confirm("Czy na pewno chcesz anulować prośbę?")) {
                location.replace(url);
            }
        }
    </script>
{% endblock %}

eproba/apps/worksheets/templates/worksheets/templates.html
{% extends 'core/base.html' %}
{% block title %}Szablony{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block extrahead %}
    <script src="{% static 'js/core/helpers.js' %}"></script>
{% endblock %}
{% block content %}
    {% if request.user.is_authenticated %}
        {% if worksheet_templates %}
            {% for worksheet_template in worksheet_templates %}
                <div class="block worksheet" id="worksheet_{{ worksheet_template.id }}">
                    <div class="box">
                        <div class="level">
                            <div class="level-left">
                                <span class="level-item title has-text-weight-medium"
                                      style="margin-bottom: 0">{{ worksheet_template.name }} </span>
                                {% if worksheet_template.organization is not None %}
                                    <img src="https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Scouting_Association_of_the_Republic_Poland.svg/440px-Scouting_Association_of_the_Republic_Poland.svg.png"
                                         alt="ZHR" style="height: 2rem" class="level-item">
                                {% endif %}
                            </div>
                            <div class="level-right is-gapless">
                                <span class="level-item icon has-tooltip-bottom has-tooltip-arrow"
                                      id="tooltip_text_{{ worksheet_template.id }}_print"
                                      data-tooltip="Drukuj szablon"><span
                                        onclick="location.href='{% url 'worksheets:print_worksheet_template' worksheet_template.id %}'"><i
                                        class="fas fa-print"></i></span></span>
                                <span class="level-item icon has-tooltip-bottom has-tooltip-arrow"
                                      id="tooltip_text_{{ worksheet_template.id }}_edit"
                                      data-tooltip="Edytuj szablon"><span
                                        onclick="location.href='{% url 'worksheets:edit_template' worksheet_template.id %}'">
                                    <i class="fa-solid fa-edit"></i></span></span>
                                <span class="level-item icon has-tooltip-bottom has-tooltip-arrow"
                                      id="tooltip_text_{{ worksheet_template.id }}_delete"
                                      data-tooltip="Usuń szablon"><span
                                        onclick="confirm_popup(null, 'Czy na pewno chcesz usunąć ten szablon?', () => {
                                                fetch('{% url 'api-templates-list' %}{{ worksheet_template.id }}/', {
                                                method: 'DELETE',
                                                headers: {
                                                'X-CSRFToken': '{{ csrf_token }}',
                                                'Content-Type': 'application/json'
                                                }
                                                })
                                                .then(response => {
                                                if (response.ok) {
                                                alert('Szablon został usunięty.');
                                                document.getElementById('worksheet_{{ worksheet_template.id }}').remove();
                                                } else {
                                                alert('Wystąpił błąd podczas usuwania szablonu.');
                                                }
                                                })
                                                .catch(error => {
                                                console.error('Error:', error);
                                                alert('Wystąpił błąd podczas usuwania szablonu.');
                                                });
                                                })">
                                     <i class="fa-solid fa-trash"></i></span></span>
                            </div>
                        </div>
                        {% if worksheet_template.description %}
                            <p style="white-space: pre-wrap;">{{ worksheet_template.description }}</p>
                        {% endif %}
                        {% if worksheet_template.template_notes %}
                            <p class="has-text-text-50" style="white-space: pre-wrap;">{{ worksheet_template.template_notes }}</p>
                        {% endif %}
                        <p><br/></p>
                        <table class="table">
                            <thead>
                            <tr>
                                <th class="is-narrow">Lp.</th>
                                <th>Zadanie</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th></th>
                                <th></th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for task in worksheet_template.tasks.all %}
                                <tr>
                                    <th>{{ forloop.counter }}</th>
                                    <td>
                                        <p>{{ task.task }}</p>
                                        {% if task.description %}
                                            <p class="has-text-text-70">{{ task.description }}</p>
                                        {% endif %}
                                        {% if task.template_notes %}
                                            <p class="has-text-text-50">{{ task.template_notes }}</p>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <button class="button is-info is-soft"
                                onclick="location.href='{% url 'worksheets:create_worksheet' %}?next={% url 'worksheets:manage_worksheets' %}&source=templates&template={{ worksheet_template.id }}'">
                            <span class="icon">
                                <i class="fa-solid fa-object-group"></i>
                            </span>
                            <span>Użyj szablonu</span>
                        </button>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="box">
                W systemie nie ma jeszcze żadnych szablonów.
            </div>
        {% endif %}
        <div class="block">
            <div class="container has-text-centered">
                <button class="button is-outlined is-primary"
                        onclick="location.href='{% url 'worksheets:create_template' %}'">
                    <span class="icon">
                        <i class="fas fa-plus"></i>
                    </span>
                    <span>Utwórz nowy szablon</span>
                </button>
            </div>
        </div>
    {% else %}
        <div class="box">
            Aby użyć szablonów musisz się najpierw zalogować.
        </div>
    {% endif %}
{% endblock %}